#!/usr/bin/env bash
# Starts the hugo server

cd "$(dirname "$0")/../../web" || exit

echo "Hugo server start"
hugo server --disableFastRender --buildFuture --buildDrafts --gc -s "." --port=1313 --bind="127.0.0.1" --watch
